name: r_icon_pro
description: "A flutter rounded icon pack with 500+ icons"
version: 0.0.1
homepage: https://github.com/Rayhan12/r_icon_pro.git
repository: https://github.com/Rayhan12/r_icon_pro.git

environment:
  sdk: ^3.5.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: false
  fonts:
    - family: RIcon
      fonts:
        - asset: lib/fonts/r-icon-pro.ttf
          style: normal
          weight: 400
  assets:
    - lib/fonts/
